import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ceneo - porównywarka cen",
  description: "Generated by create next app",
};

export default async function CeneoLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="flex flex-row">{children}</div>;
}
