import Nav from "@/components/ceneo/shared/search/Nav";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ceneo - porównywarka cen",
  description: "Generated by create next app",
};

export default async function CeneoLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col w-full bg-slate-100 h-screen">
      <Nav />
      {children}
    </div>
  );
}
