import Footer from "@/components/ceneo/shared/footer/Footer";
import NavBasket from "@/components/ceneo/shared/nav/NavBasket";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ceneo - porównywarka cen",
  description: "Generated by create next app",
};

export default async function CeneoLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col w-full min-h-screen bg-slate-100">
      <NavBasket />
      {children}
    </div>
  );
}
